--------------------------------------------------------
--  Constraints for Table AI_TABLE_EXTRACT
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."AI_TABLE_EXTRACT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."AI_TABLE_EXTRACT" MODIFY ("ID" NOT NULL ENABLE);
