
   COMMENT ON COLUMN "EBA_COUNTRY_ORGANIZATIONS"."ID" IS 'Auto-incrementing primary key';
   COMMENT ON COLUMN "EBA_COUNTRY_ORGANIZATIONS"."CODE" IS 'The region code';
   COMMENT ON COLUMN "EBA_COUNTRY_ORGANIZATIONS"."NAME" IS 'The region name';
   COMMENT ON TABLE "EBA_COUNTRY_ORGANIZATIONS"  IS 'Regions specifically for the orgnaization';