--------------------------------------------------------
--  Ref Constraints for Table EBA_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_COUNTRIES" ADD CONSTRAINT "EBA_COUNTRY_REGIONS_FK" FOREIGN KEY ("REGION_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_COUNTRY_REGIONS" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."EBA_COUNTRIES" ADD CONSTRAINT "EBA_COUNTRY_SUB_REGIONS_FK" FOREIGN KEY ("SUB_REGION_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_COUNTRY_SUB_REGIONS" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."EBA_COUNTRIES" ADD CONSTRAINT "EBA_COUNTRY_INTERMEDIATES_FK" FOREIGN KEY ("INTERMEDIATE_REGION_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_COUNTRY_INTERMEDIATES" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."EBA_COUNTRIES" ADD CONSTRAINT "EBA_COUNTRY_ORGANIZATIONS_FK" FOREIGN KEY ("ORGANIZATION_REGION_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_COUNTRY_ORGANIZATIONS" ("ID") ON DELETE SET NULL ENABLE;
