--------------------------------------------------------
--  Ref Constraints for Table EBA_PROJECT_TASK_LINKS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_LINKS" ADD CONSTRAINT "EBA_PROJECT_TSK_LINK_PRJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_LINKS" ADD CONSTRAINT "EBA_PROJECT_TSK_LINK_TSK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_PROJECT_TASKS" ("ID") ON DELETE CASCADE ENABLE;
