--------------------------------------------------------
--  Ref Constraints for Table EBA_PROJECT_TASKS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASKS" ADD CONSTRAINT "EBA_PROJECT_TASK_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASKS" ADD CONSTRAINT "EBA_PROJECT_TASK_MSTONE_FK" FOREIGN KEY ("MILESTONE_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_PROJECT_MILESTONES" ("ID") ON DELETE SET NULL ENABLE;
