REM INSERTING into WKSP_OACLABWS.EBA_COUNTRY_ORGANIZATIONS
SET DEFINE OFF;
Insert into WKSP_OACLABWS.EBA_COUNTRY_ORGANIZATIONS (ID,CODE,NAME) values (10,'NA','North America');
Insert into WKSP_OACLABWS.EBA_COUNTRY_ORGANIZATIONS (ID,CODE,NAME) values (20,'EMEA','Europe, Middle East, and Africa');
Insert into WKSP_OACLABWS.EBA_COUNTRY_ORGANIZATIONS (ID,CODE,NAME) values (30,'APAC','  Asia Pacific');
Insert into WKSP_OACLABWS.EBA_COUNTRY_ORGANIZATIONS (ID,CODE,NAME) values (40,'LAD',' Latin America');
