REM INSERTING into WKSP_OACLABWS.EBA_COUNTRY_REGIONS
SET DEFINE OFF;
Insert into WKSP_OACLABWS.EBA_COUNTRY_REGIONS (ID,NAME) values (10,'America');
Insert into WKSP_OACLABWS.EBA_COUNTRY_REGIONS (ID,NAME) values (20,'Europe');
Insert into WKSP_OACLABWS.EBA_COUNTRY_REGIONS (ID,NAME) values (30,'Asia');
Insert into WKSP_OACLABWS.EBA_COUNTRY_REGIONS (ID,NAME) values (40,'Oceania');
Insert into WKSP_OACLABWS.EBA_COUNTRY_REGIONS (ID,NAME) values (50,'Africa');
