--------------------------------------------------------
--  Ref Constraints for Table EBA_PROJECT_TASK_TODOS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" ADD CONSTRAINT "EBA_PROJ_TASK_TODO_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" ADD CONSTRAINT "EBA_PROJECT_TSK_TODO_TSK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "WKSP_OACLABWS"."EBA_PROJECT_TASKS" ("ID") ON DELETE CASCADE ENABLE;
