--------------------------------------------------------
--  Ref Constraints for Table HOL_TASKS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" ADD CONSTRAINT "HOL_TASKS_PROJECT_ID_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "WKSP_OACLABWS"."HOL_PROJECTS" ("ID") ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" ADD CONSTRAINT "HOL_TASKS_MILESTONE_ID_FK" FOREIGN KEY ("MILESTONE_ID")
	  REFERENCES "WKSP_OACLABWS"."HOL_MILESTONES" ("ID") ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" ADD CONSTRAINT "HOL_TASKS_ASSIGNEE_FK" FOREIGN KEY ("ASSIGNEE")
	  REFERENCES "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" ("ID") ENABLE;
