REM INSERTING into WKSP_OACLABWS.APPROVAL_LEVELS
SET DEFINE OFF;
Insert into WKSP_OACLABWS.APPROVAL_LEVELS (LEVEL_ID,MGR_NAME,MGR_EMAIL,LEVEL_CODE) values (10,'JANE','jane@expenseteam.com',1);
Insert into WKSP_OACLABWS.APPROVAL_LEVELS (LEVEL_ID,MGR_NAME,MGR_EMAIL,LEVEL_CODE) values (20,'MATT','martin@expenseteam.com',1);
Insert into WKSP_OACLABWS.APPROVAL_LEVELS (LEVEL_ID,MGR_NAME,MGR_EMAIL,LEVEL_CODE) values (30,'BO','bo@expenseteam.com',2);
Insert into WKSP_OACLABWS.APPROVAL_LEVELS (LEVEL_ID,MGR_NAME,MGR_EMAIL,LEVEL_CODE) values (40,'CLARA','clara@expenseteam.com',2);
Insert into WKSP_OACLABWS.APPROVAL_LEVELS (LEVEL_ID,MGR_NAME,MGR_EMAIL,LEVEL_CODE) values (50,'SUSIE','susie@expenseteam.com',3);
