REM INSERTING into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250
SET DEFINE OFF;
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'1','60','1','aaae.medicallake.net','Tools Standardization','Proin sit amet massa eu.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'2','39','1','aaae.surfcity.net','BKI System Review','Vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'3','40','1','aaae.lakenormanofcatawba.net','ELK Site','Venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque tortor odio, feugiat eget sagittisvel, pretium ut metus. Duis et commodo arcu, in vestibulum tellus. In sollicitudin nisi mi, pharetra gravida ex semper ut.Donec nibh sapien, hendrerit quis varius eget, malesuada vitae turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vivamus sapien sem, volutpat vitae luctus vitae, pretium a ligula. Donec eget lectus.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'4','84','1','aaae.lakenormanofcatawba.net','Eloqua Marketing Program','Ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque tortor odio, feugiat eget sagittisvel, pretium ut.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'5','53','1','aaab.angoon.com','Systems Automation','Ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'6','64','1','aaac.windsorplace.com','Angular Library Upgrade','Quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'7','41','1','aaab.koeking.com','Blockchain System Rollout','Elementum sodales. Proin sit amet massa eu.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'8','54','1','aaag.twinvalley.gov','Compendium GA','Consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'9','2','1','aaac.friedensburg.com','Digital Asset Management','Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque tortor odio, feugiat eget sagittisvel, pretium ut metus. Duis et commodo arcu, in vestibulum tellus. In sollicitudin nisi mi, pharetra gravida ex semper ut.Donec nibh sapien, hendrerit quis varius eget, malesuada vitae turpis. Lorem ipsum dolor sit amet,.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
Insert into WKSP_OACLABWS.APX$ERR$HOL_LINKS$136250 (ORA_ERR_NUMBER$,ORA_ERR_MESG$,ORA_ERR_ROWID$,ORA_ERR_OPTYP$,ORA_ERR_TAG$,ID,TASK_ID,ROW_VERSION,URL,NAME,DESCRIPTION,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2291,'ORA-02291: integrity constraint (WKSP_OACLABWS.HOL_LINKS_TASK_ID_FK) violated - parent key not found
',null,'I',null,'10','45','1','aaac.nomexy.com','Terraform System Scripting','Cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque tortor odio, feugiat eget sagittisvel, pretium ut metus. Duis et commodo arcu, in vestibulum tellus. In sollicitudin nisi mi, pharetra gravida ex semper ut.Donec nibh sapien, hendrerit quis varius eget, malesuada vitae turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vivamus sapien sem, volutpat vitae luctus.','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN','7/9/2025','MRVIRPURA_DIGVIJAY@YAHOO.CO.IN');
