REM INSERTING into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES
SET DEFINE OFF;
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (10,'Western Africa');
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (20,'Central America');
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (30,'Southern Africa');
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (40,'South America');
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (50,'Eastern Africa');
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (60,'Caribbean');
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (70,'Channel Islands');
Insert into WKSP_OACLABWS.EBA_COUNTRY_INTERMEDIATES (ID,NAME) values (80,'Middle Africa');
