--------------------------------------------------------
--  Constraints for Table APPROVAL_LEVELS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."APPROVAL_LEVELS" MODIFY ("LEVEL_ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."APPROVAL_LEVELS" MODIFY ("LEVEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."APPROVAL_LEVELS" ADD CONSTRAINT "APPROVAL_LEVELS_PK" PRIMARY KEY ("LEVEL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
