--------------------------------------------------------
--  Constraints for Table DOCAI_RESPONSE
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."DOCAI_RESPONSE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."DOCAI_RESPONSE" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."DOCAI_RESPONSE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."DOCAI_RESPONSE" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."DOCAI_RESPONSE" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."DOCAI_RESPONSE" ADD CONSTRAINT "DOCAI_RESPONSE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
