--------------------------------------------------------
--  Constraints for Table EBA_PROJECT_COMMENTS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" MODIFY ("COMMENT_TEXT" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_COMMENTS" ADD CONSTRAINT "EBA_PROJECT_COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
