--------------------------------------------------------
--  Constraints for Table EBA_PROJECT_TASK_TODOS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_TASK_TODOS" ADD CONSTRAINT "EBA_PROJECT_TASK_TODOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
