--------------------------------------------------------
--  Constraints for Table EBA_COUNTRY_REGIONS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_COUNTRY_REGIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_COUNTRY_REGIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_COUNTRY_REGIONS" ADD CONSTRAINT "EBA_COUNTRY_REGION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
