--------------------------------------------------------
--  Constraints for Table EBA_PROJECT_STATUS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" ADD CONSTRAINT "EBA_PROJECT_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."EBA_PROJECT_STATUS" ADD CONSTRAINT "EBA_PROJECT_STATUS_UK" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
