--------------------------------------------------------
--  Constraints for Table HOL_TO_DOS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" MODIFY ("TODO" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TO_DOS" ADD CONSTRAINT "HOL_TO_DOS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
