--------------------------------------------------------
--  Constraints for Table HOL_TASKS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" ADD CONSTRAINT "HOL_TASKS_IS_COMPLETE_YN_CK" CHECK (is_complete_yn in ('Y','N')) ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."HOL_TASKS" ADD CONSTRAINT "HOL_TASKS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
