--------------------------------------------------------
--  Constraints for Table HOL_LINKS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_LINKS" ADD CONSTRAINT "HOL_LINKS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
