--------------------------------------------------------
--  Constraints for Table HOL_TEAM_MEMBERS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_TEAM_MEMBERS" ADD CONSTRAINT "HOL_TEAM_MEMBERS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
