--------------------------------------------------------
--  Constraints for Table HOL_MILESTONES
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("DUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_MILESTONES" ADD CONSTRAINT "HOL_MILESTONES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
