--------------------------------------------------------
--  Constraints for Table HOL_PROJECTS
--------------------------------------------------------

  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("PROJECT_LEAD" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" ADD CONSTRAINT "HOL_PROJECTS_STATUS_CK" CHECK (status in ('ASSIGNED','IN-PROGRESS','COMPLETED')) ENABLE;
  ALTER TABLE "WKSP_OACLABWS"."HOL_PROJECTS" ADD CONSTRAINT "HOL_PROJECTS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
