--------------------------------------------------------
--  DDL for Table APX$ERR$HOL_LINKS$136250
--------------------------------------------------------

  CREATE TABLE "WKSP_OACLABWS"."APX$ERR$HOL_LINKS$136250" 
   (	"ORA_ERR_NUMBER$" NUMBER, 
	"ORA_ERR_MESG$" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"ORA_ERR_ROWID$" UROWID (4000), 
	"ORA_ERR_OPTYP$" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"ORA_ERR_TAG$" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TASK_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ROW_VERSION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URL" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_BY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_OACLABWS"."APX$ERR$HOL_LINKS$136250"  IS 'DML Error Logging table for "HOL_LINKS"';
