--------------------------------------------------------
--  DDL for Table DM$PADOC_MODEL
--------------------------------------------------------

  CREATE TABLE "WKSP_OACLABWS"."DM$PADOC_MODEL" 
   (	"PNAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"INPUT_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
