--------------------------------------------------------
--  DDL for Table DM$P5DOC_MODEL
--------------------------------------------------------

  CREATE TABLE "WKSP_OACLABWS"."DM$P5DOC_MODEL" 
   (	"PNAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"ONUM" NUMBER, 
	"PXNO" NUMBER, 
	"RNUM" NUMBER, 
	"CKNO" NUMBER, 
	"CHUNK" RAW(2000)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
